//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotoCommunity.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О себе.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить комментарий.
        /// </summary>
        public static string AddComment {
            get {
                return ResourceManager.GetString("AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить фото.
        /// </summary>
        public static string AddPhoto {
            get {
                return ResourceManager.GetString("AddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фото успешно добавлено..
        /// </summary>
        public static string AddPhotoSuccess {
            get {
                return ResourceManager.GetString("AddPhotoSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аватар.
        /// </summary>
        public static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад.
        /// </summary>
        public static string BackLink {
            get {
                return ResourceManager.GetString("BackLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сменить пароль.
        /// </summary>
        public static string ChangePass {
            get {
                return ResourceManager.GetString("ChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сменить парль.
        /// </summary>
        public static string ChangePassLink {
            get {
                return ResourceManager.GetString("ChangePassLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Форма смены пароля.
        /// </summary>
        public static string ChangePassMessage {
            get {
                return ResourceManager.GetString("ChangePassMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Смена пароля.
        /// </summary>
        public static string ChangePassSubmitButton {
            get {
                return ResourceManager.GetString("ChangePassSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваш пароль изменен..
        /// </summary>
        public static string ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("ChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбирите фото.
        /// </summary>
        public static string ChosePhoto {
            get {
                return ResourceManager.GetString("ChosePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комментарий.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на комментариев.
        /// </summary>
        public static string CommentCount {
            get {
                return ResourceManager.GetString("CommentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комментарии.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Щелкните здесь для входа.
        /// </summary>
        public static string ConfirmEmailLink {
            get {
                return ResourceManager.GetString("ConfirmEmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Благодарим за подтверждение электронной почты..
        /// </summary>
        public static string ConfirmEmailMessage {
            get {
                return ResourceManager.GetString("ConfirmEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущий пароль.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата публикации.
        /// </summary>
        public static string DatePublic {
            get {
                return ResourceManager.GetString("DatePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить это фото?.
        /// </summary>
        public static string DeletePhotoMessage {
            get {
                return ResourceManager.GetString("DeletePhotoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string DeleteSubmitButton {
            get {
                return ResourceManager.GetString("DeleteSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить этого пользователя?.
        /// </summary>
        public static string DeleteUserMessage {
            get {
                return ResourceManager.GetString("DeleteUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание фото.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На указанный электронный адрес отправлены дальнейшие инструкции по завершению регистрации.
        /// </summary>
        public static string DisplayEmailMessage {
            get {
                return ResourceManager.GetString("DisplayEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать.
        /// </summary>
        public static string EditLink {
            get {
                return ResourceManager.GetString("EditLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать профиль.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сменить аватар.
        /// </summary>
        public static string EditProfileChangeAvatar {
            get {
                return ResourceManager.GetString("EditProfileChangeAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваш профиль успешно изменён..
        /// </summary>
        public static string EditProfileSuccess {
            get {
                return ResourceManager.GetString("EditProfileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Электронная почта.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чтобы выполнить данное действие, выполните вход с правами администратора.
        /// </summary>
        public static string ErrorAdminOnly {
            get {
                return ResourceManager.GetString("ErrorAdminOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оценить фотографию можно только один раз.
        /// </summary>
        public static string ErrorDoubleLike {
            get {
                return ResourceManager.GetString("ErrorDoubleLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коментировать фотографии могут только пользователи системмы.
        /// </summary>
        public static string ErrorGuestComment {
            get {
                return ResourceManager.GetString("ErrorGuestComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оценивать фотографии могут только пользователи системмы.
        /// </summary>
        public static string ErrorGuestLike {
            get {
                return ResourceManager.GetString("ErrorGuestLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный логин или пароль.
        /// </summary>
        public static string ErrorIncorrectLoginOrPass {
            get {
                return ResourceManager.GetString("ErrorIncorrectLoginOrPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не подтвержден email.
        /// </summary>
        public static string ErrorNotConfirmed {
            get {
                return ResourceManager.GetString("ErrorNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле Телефон содержит недопустимые символы.
        /// </summary>
        public static string ErrorPhoneFormat {
            get {
                return ResourceManager.GetString("ErrorPhoneFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Такого фото не существует в данной системе.
        /// </summary>
        public static string ErrorPhotoNotExist {
            get {
                return ResourceManager.GetString("ErrorPhotoNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Такой пользователь не зарегистрирован в данной системе.
        /// </summary>
        public static string ErrorUserNotExist {
            get {
                return ResourceManager.GetString("ErrorUserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполните вход как пользователь чтобы выполнить это действие.
        /// </summary>
        public static string ErrorUserOnly {
            get {
                return ResourceManager.GetString("ErrorUserOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле Электронная почта заполнено не корректно.
        /// </summary>
        public static string ErrorValidEmail {
            get {
                return ResourceManager.GetString("ErrorValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправка ссылки по электронной почте.
        /// </summary>
        public static string ForgotPasswordButtonText {
            get {
                return ResourceManager.GetString("ForgotPasswordButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверьте электронную почту, чтобы сбросить пароль..
        /// </summary>
        public static string ForgotPasswordConfirmMessage {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите адрес электронной почты..
        /// </summary>
        public static string ForgotPasswordMessage {
            get {
                return ResourceManager.GetString("ForgotPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Галерея.
        /// </summary>
        public static string GalleryTitle {
            get {
                return ResourceManager.GetString("GalleryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;&gt;здесь&lt;/a&gt;.
        /// </summary>
        public static string Here {
            get {
                return ResourceManager.GetString("Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мне нравится.
        /// </summary>
        public static string Like {
            get {
                return ResourceManager.GetString("Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить.
        /// </summary>
        public static string LoadLink {
            get {
                return ResourceManager.GetString("LoadLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Забыли пароль?.
        /// </summary>
        public static string LoginForgotLink {
            get {
                return ResourceManager.GetString("LoginForgotLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация нового пользователя.
        /// </summary>
        public static string LoginRegisterLink {
            get {
                return ResourceManager.GetString("LoginRegisterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнить вход.
        /// </summary>
        public static string LoginSubmitButton {
            get {
                return ResourceManager.GetString("LoginSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердите вашу учетную запись, щелкнув &lt;a href=&quot;.
        /// </summary>
        public static string MailConfirmationBody {
            get {
                return ResourceManager.GetString("MailConfirmationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение учетной записи.
        /// </summary>
        public static string MailConfirmationHeader {
            get {
                return ResourceManager.GetString("MailConfirmationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сбросьте ваш пароль, щелкнув &lt;a href=&quot;.
        /// </summary>
        public static string MailResetPassBody {
            get {
                return ResourceManager.GetString("MailResetPassBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сброс пароля.
        /// </summary>
        public static string MailResetPassHeader {
            get {
                return ResourceManager.GetString("MailResetPassHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На главную.
        /// </summary>
        public static string MainPageLink {
            get {
                return ResourceManager.GetString("MainPageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Админ панель.
        /// </summary>
        public static string MenuAdmin {
            get {
                return ResourceManager.GetString("MenuAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Галерея.
        /// </summary>
        public static string MenuGallery {
            get {
                return ResourceManager.GetString("MenuGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти.
        /// </summary>
        public static string MenuLogin {
            get {
                return ResourceManager.GetString("MenuLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти.
        /// </summary>
        public static string MenuLogout {
            get {
                return ResourceManager.GetString("MenuLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        public static string MenuRegister {
            get {
                return ResourceManager.GetString("MenuRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователи.
        /// </summary>
        public static string MenuUsers {
            get {
                return ResourceManager.GetString("MenuUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мой профиль.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый пароль.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый пароль подтверждение.
        /// </summary>
        public static string NewPasswordConfirm {
            get {
                return ResourceManager.GetString("NewPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка 404. Ресурс не найден.
        /// </summary>
        public static string NotFoundMessage {
            get {
                return ResourceManager.GetString("NotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Из.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Страница.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение пароля.
        /// </summary>
        public static string PasswordConfirmation {
            get {
                return ResourceManager.GetString("PasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение {0} должно содержать не менее {2} символов..
        /// </summary>
        public static string PasswordSequrity {
            get {
                return ResourceManager.GetString("PasswordSequrity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль и его подтверждение не совпадают..
        /// </summary>
        public static string PasswordsNotEqual {
            get {
                return ResourceManager.GetString("PasswordsNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название фото.
        /// </summary>
        public static string PhotoName {
            get {
                return ResourceManager.GetString("PhotoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рейтинг.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создайте новую учетную запись..
        /// </summary>
        public static string RegisterMessage {
            get {
                return ResourceManager.GetString("RegisterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        public static string RegisterSubmitButton {
            get {
                return ResourceManager.GetString("RegisterSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запомнить меня.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string SaveLink {
            get {
                return ResourceManager.GetString("SaveLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найти.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон.
        /// </summary>
        public static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить фото.
        /// </summary>
        public static string TitleAddPhoto {
            get {
                return ResourceManager.GetString("TitleAddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Смена пароля.
        /// </summary>
        public static string TitleChangePass {
            get {
                return ResourceManager.GetString("TitleChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение почты.
        /// </summary>
        public static string TitleConfirmEmail {
            get {
                return ResourceManager.GetString("TitleConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить фото.
        /// </summary>
        public static string TitleDeletePhoto {
            get {
                return ResourceManager.GetString("TitleDeletePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить пользователя.
        /// </summary>
        public static string TitleDeleteUser {
            get {
                return ResourceManager.GetString("TitleDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подробно.
        /// </summary>
        public static string TitleDetails {
            get {
                return ResourceManager.GetString("TitleDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завершение регистрации.
        /// </summary>
        public static string TitleDisplayEmail {
            get {
                return ResourceManager.GetString("TitleDisplayEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать.
        /// </summary>
        public static string TitleEdit {
            get {
                return ResourceManager.GetString("TitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать профиль.
        /// </summary>
        public static string TitleEditProfile {
            get {
                return ResourceManager.GetString("TitleEditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Восстановление пароля.
        /// </summary>
        public static string TitleForgotPassword {
            get {
                return ResourceManager.GetString("TitleForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение пароля.
        /// </summary>
        public static string TitleForgotPasswordConfirm {
            get {
                return ResourceManager.GetString("TitleForgotPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнить вход.
        /// </summary>
        public static string TitleLogin {
            get {
                return ResourceManager.GetString("TitleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мой профиль.
        /// </summary>
        public static string TitleMyProfile {
            get {
                return ResourceManager.GetString("TitleMyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка 404.
        /// </summary>
        public static string TitleNotFound {
            get {
                return ResourceManager.GetString("TitleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        public static string TitleRegister {
            get {
                return ResourceManager.GetString("TitleRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Просмотр фото.
        /// </summary>
        public static string TitleShow {
            get {
                return ResourceManager.GetString("TitleShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователи.
        /// </summary>
        public static string TitleUsers {
            get {
                return ResourceManager.GetString("TitleUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мне не нравится.
        /// </summary>
        public static string Unlike {
            get {
                return ResourceManager.GetString("Unlike", resourceCulture);
            }
        }
    }
}
