// <auto-generated />
namespace PhotoCommunity.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class likestolike : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(likestolike));
        
        string IMigrationMetadata.Id
        {
            get { return "201707131959101_likes to like"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
