// <auto-generated />
namespace PhotoCommunity.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changetypeofImageUser_Idtostring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changetypeofImageUser_Idtostring));
        
        string IMigrationMetadata.Id
        {
            get { return "201707071146091_change type of Image User_Id to string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
