// <auto-generated />
namespace PhotoCommunity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeCommentdb_tableApplicationUserinstedofstring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeCommentdb_tableApplicationUserinstedofstring));
        
        string IMigrationMetadata.Id
        {
            get { return "201708151014085_change Comment db_table ApplicationUser insted of string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
